version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: webrtc/tools/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: tools/scripts/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: css/css-writing-modes/tools/generators/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: docs/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: resources/test/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: tools/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: tools/wpt/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: tools/wptrunner/
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
