dist: trusty
sudo: required
language: python
branches:
  only:
    - master
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
before_install:
  # This needs be sourced as it sets various env vars
  - . ./tools/ci/before_install.sh
install:
  - ./tools/ci/install.sh
  - which virtualenv
matrix:
  fast_finish: true
  include:
    - name: "infrastructure/ tests (Safari TP)"
      os: osx
      language: generic
      env: JOB=lint SCRIPT=tools/ci/ci_lint.sh
script:
  - python --version
  - sudo hdiutil attach tools/ci/SafariTechnologyPreview.dmg
  - sudo installer -pkg "/Volumes/Safari Technology Preview/Safari Technology Preview.pkg" -target /
  # source: https://github.com/bocoup/results-collection/blob/04116e0a52e891171236427ff348d8e52dd2d342/src/scripts/safari-enable-automation.sh
  - ./tools/ci/safari-enable-automation.sh
  # https://github.com/web-platform-tests/wpt/blob/master/docs/_running-tests/safari.md
  - defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically 1
  #- security add-trusted-cert -k "$(security default-keychain | cut -d\" -f2)" tools/certs/cacert.pem
  - ./wpt make-hosts-file | sudo tee -a /etc/hosts
  - no_proxy='*' ./wpt run --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --install-fonts --log-wptreport=wpt_report.json safari infrastructure/

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/meta
notifications:
  email:
    on_success: never
    on_failure: always
