dist: trusty
sudo: required
language: python
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
before_install:
  - git submodule update --init --recursive
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -U setuptools
  - pip install -U requests
env:  # required at the top-level for allow_failures to work below
matrix:
  include:
    - os: linux
      sudo: required
      python: "2.7"
      addons:
        apt:
          packages:
            - libappindicator1
            - fonts-liberation
      env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - SCRIPT=ci_stability.sh PRODUCT=chrome:unstable
  exclude:
    - env:  # exclude empty env from the top-level above
script:
  - bash $SCRIPT
cache:
  directories:
    - $HOME/.cache/pip
