dist: trusty
sudo: required
language: python
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
script:
  - echo $TRAVIS_COMMIT_RANGE
  - git log --oneline --graph --max-count 20
  - REF=$(python -c 'import os; print os.environ.get("TRAVIS_COMMIT_RANGE").split(".")[0]'); git diff --name-only $REF..
cache:
  directories:
    - $HOME/.cache/pip
