dist: trusty
sudo: required
language: python
branches:
  only:
    - master
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
  jwt:
    secure: cSR6NxySVedPmudbyPTl5uSQWVMvMIp78yTqnAp8MpXdTrTuZTnCXIDowjxoIy+PrXKt/qrHRzCXG/TL2UsWztr1Xe/Ytqhl1BJMB+NKPAeH5hd5br7wYgiQ89j/ZyCzgjEpR1U1u9eOgpXVrvotX671sLJ4jJ5h4HVzAXDO/jPaVIOV/UiZhK89tRquxqSurfLjU7koXyFJbbVvxDgNA3AalO6rWSx2Qsc9jMJGp9gJfV2Jb3sBGZNRgqDQeObkF/wT01auOnurx62Jr9KXJPQ87QNqtBqSA6GWTCoGDo5AUuR2wGlbYYCNClt6YtGcEe5a7kDNdCl1ZKc2SgyMEgZnTfKlW+lOKw8La9ZD2JeymDtUN6CN18UmC4X7+nsJaY1Vm9MyDieKG4t6hAgMi2GlKxBRU0SNC5bU0Qm6aI7OVKCcKOb295oWE04ywp970esgCtTCxHOBJ6nuPiccjYaBN6oqxkFbPWW0vxAZtp/t55qkNfOWjcHvZd3KPeMYpDKZv8vjlGvWkVP9mdnuH4wX5/xkgtLVX93gg8sw52SHths7kpFjyx6wwhdcLCORGOsQ3+Kw1IG/dEJmEocnAF4O3e2fFJ2oMHDuw9T2NdqcLRbLmv2PYnETnwWRuCC0CYLKL5vnm6G4AGLgOMFjgEDT/VRESXKZA4oWnZiglgU=
before_install:
  - . ./tools/ci/before_install.sh
install:
  - ./tools/ci/install.sh
env:  # required at the top-level for allow_failures to work below
  global:
    - SAUCE_USERNAME=lukebjerring
matrix:
  fast_finish: true
  include:
    - os: linux
      python: "2.7"
      env:
        - JOB=manifest_upload SCRIPT=tools/ci/ci_manifest.sh
        - secure: "FrlMkMZiwggnhJbLiLxZ4imtXxuzFNozty94g1mneMPEVLrnyhb6c/g2SwN37KKU0WSDlGTz26IYnFvo1ftfSOx+sjRz0HqwW7JnrXULKYo7jiPttIcmeJxlSVeW9yS4blbLaBakytHjSnsf+za7bAaf1aS7RRAtAINgifA6Chg="
      deploy:
        provider: releases
        api_key:
          secure: "EljDx50oNpDLs7rzwIv+z1PxIgB5KMnx1W0OQkpNvltR0rBW9g/aQaE+Z/c8M/sPqN1bkvKPybKzGKjb6j9Dw3/EJhah4SskH78r3yMAe2DU/ngxqqjjfXcCc2t5MKxzHAILTAxqScPj2z+lG1jeK1Z+K5hTbSP9lk+AvS0D16w="
        file: $WPT_MANIFEST_FILE.gz
        skip_cleanup: true
    - os: linux
      python: "2.7"
      env: JOB=lint SCRIPT=tools/ci/ci_lint.sh
    - os: linux
      python: "2.7"
      env: JOB=update_built SCRIPT=tools/ci/ci_built_diff.sh
    - os: linux
      python: "2.7"
      env: JOB=build_css SCRIPT=css/build-css-testsuites.sh
    - os: linux
      python: "2.7"
      addons:
        apt:
          packages:
            - libnss3-tools
      env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=firefox:nightly
    - os: linux
      sudo: required
      python: "2.7"
      addons:
        apt:
          packages:
            - libappindicator1
            - fonts-liberation
      env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=chrome:unstable
    - os: linux
      python: "2.7"
      env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=sauce:safari:10.0 PLATFORM='macOS 10.12'
    - os: linux
      python: "2.7"
      env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=sauce:MicrosoftEdge:14.14393 PLATFORM='Windows 10'
    - python: 2.7
      env: JOB=tools_unittest TOXENV=py27 HYPOTHESIS_PROFILE=ci SCRIPT=tools/ci/ci_tools_unittest.sh
    - python: 3.6
      env: JOB=tools_unittest TOXENV=py36 HYPOTHESIS_PROFILE=ci SCRIPT=tools/ci/ci_tools_unittest.sh
    - python: pypy-5.4
      env: JOB=tools_unittest TOXENV=pypy HYPOTHESIS_PROFILE=ci SCRIPT=tools/ci/ci_tools_unittest.sh
    - python: 2.7
      env: JOB=resources_unittest TOXENV=py27 SCRIPT=tools/ci/ci_resources_unittest.sh
    - python: 2.7
      addons:
        apt:
          packages:
            - libnss3-tools
      env: JOB=wpt_integration TOXENV=py27 SCRIPT=tools/ci/ci_wpt.sh
  exclude:
    - env:  # exclude empty env from the top-level above
  allow_failures:
    - env: JOB=build_css SCRIPT=css/build-css-testsuites.sh
    - env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=chrome:unstable
    - env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=sauce:MicrosoftEdge:14.14393 PLATFORM='Windows 10'
    - env:
        - secure: "YTSXPwI0DyCA1GhYrLT9KMEV6b7QQKuEeaQgeFDP38OTzJ1+cIj3CC4SRNqbnJ/6SJwPGcdqSxLuV8m4e5HFFnyCcQnJe6h8EMsTehZ7W3j/fP9UYrJqYqvGpe3Vj3xblO5pwBYmq7sg3jAmmuCgAgOW6VGf7cRMucrsmFeo7VM="
        - JOB=stability SCRIPT=tools/ci/ci_stability.sh PRODUCT=sauce:safari:10.0 PLATFORM='macOS 10.12'
script:
  - ./tools/ci/run.sh
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/meta
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://pulls-staging.web-platform-tests.org/api/build
