dist: trusty
language: python
addons:
  hosts:
  - web-platform.test
  - www.web-platform.test
  - www1.web-platform.test
  - www2.web-platform.test
  - xn--n8j6ds53lwwkrqhv28a.web-platform.test
  - xn--lve-6lad.web-platform.test
before_install:
- git submodule update --init --recursive
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- pip install -U setuptools
- pip install -U requests
matrix:
  include:
  - os: linux
    python: '2.7'
    env:
    - SCRIPT=ci_lint.sh
  - os: linux
    python: '2.7'
    env:
    - SCRIPT=ci_built_diff.sh
  - os: linux
    python: '2.7'
    addons:
      apt:
        packages:
        - libnss3-tools
    env:
    - secure: RbyExCPn1l6Q25JCsg72G+eSaaSGpbekCrhcr4SD1WzU3DBFuc+oSq5BWaYuIzgOB51z0gEF6oL2Y0l2WDOZl9FmnB+D0/IDhJQkdXb071ajtQ30s2mW5ImSThJ6zVNwk89KU9zskKoiqyjrmkO6HcTLOwOYxoNKsywxtMgaO/Jk3cxttSa3at3QMrtS+t/pdH5PfeiXiXDqxUQng9ePMVnw4LFBvXf7huiMJdTSQ5f+E+ZwIna+hkHYrJpOSZvw3EpoCxEggSlZvx9hKrWDFdq0GYyHSIa2tPlr6n1MCsOocDttwLtmEu5X7otPauzEaUjBd6FWXXbOBk24sh4KKScEmQrbNoBnlONJTLgHMJYLdcdaYfaYxHcZVObomv849MDjcfo5/TgJtuTIuSQG/eT7MHT3shcEeqH2A79sESmFQW6WdBBOJmWuxc+BJhtHi3yb5RPM9xj8UyCg7QK+c9ZQ1EJR8lQExd1vqGZSeaYxsZjW4E5zymJEgbp915O4BSvZARwDR2rSJTSA44tbs66WFWTe+TXisE73x9fXmJHV0Tt3dmDOquBDBmuIrXb4Haz8XcvpQBmkoCBsh+lXytsgA7HCs1Pdit0t+FTZYK5LImqrX1pR4D5VgteiJ4JYdLYyg0Jqe/jFlHcv3SIiLNT4HWygr8FRwGIpj+ytxRo=
    - SCRIPT=ci_stability.sh
    - PRODUCT=firefox
  - os: linux
    sudo: required
    python: '2.7'
    addons:
      apt:
        packages:
        - libappindicator1
        - fonts-liberation
    env:
    - secure: RbyExCPn1l6Q25JCsg72G+eSaaSGpbekCrhcr4SD1WzU3DBFuc+oSq5BWaYuIzgOB51z0gEF6oL2Y0l2WDOZl9FmnB+D0/IDhJQkdXb071ajtQ30s2mW5ImSThJ6zVNwk89KU9zskKoiqyjrmkO6HcTLOwOYxoNKsywxtMgaO/Jk3cxttSa3at3QMrtS+t/pdH5PfeiXiXDqxUQng9ePMVnw4LFBvXf7huiMJdTSQ5f+E+ZwIna+hkHYrJpOSZvw3EpoCxEggSlZvx9hKrWDFdq0GYyHSIa2tPlr6n1MCsOocDttwLtmEu5X7otPauzEaUjBd6FWXXbOBk24sh4KKScEmQrbNoBnlONJTLgHMJYLdcdaYfaYxHcZVObomv849MDjcfo5/TgJtuTIuSQG/eT7MHT3shcEeqH2A79sESmFQW6WdBBOJmWuxc+BJhtHi3yb5RPM9xj8UyCg7QK+c9ZQ1EJR8lQExd1vqGZSeaYxsZjW4E5zymJEgbp915O4BSvZARwDR2rSJTSA44tbs66WFWTe+TXisE73x9fXmJHV0Tt3dmDOquBDBmuIrXb4Haz8XcvpQBmkoCBsh+lXytsgA7HCs1Pdit0t+FTZYK5LImqrX1pR4D5VgteiJ4JYdLYyg0Jqe/jFlHcv3SIiLNT4HWygr8FRwGIpj+ytxRo=
    - SCRIPT=ci_stability.sh
    - PRODUCT=chrome
script:
- bash $SCRIPT
cache:
  directories:
  - "$HOME/.cache/pip"
notifications:
  email:
    on_success: never
    on_failure: always
